name: Simple testwf2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Run a one-line script
        run: |
          for i in `ls -lrt | awk '{ print $9}'`; do
          echo "fichier : $i"
          cat $i
          done
          echo `pwd`
          cp toto.txt toto.bak

      - name: Download logs
        uses: actions/download-artifact@v4
        with:
            name: logs-all
            path: .
